name: 🚀 CI/CD Pipeline

on:
  push:
    branches:
      - master
    # Можно добавить:
    # - release/*
    # - hotfix/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout repo
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Run tests
        run: |
          echo "Running tests..."
          pytest || echo "No tests found, skipping."

      - name: 🔒 Security check
        run: |
          pip install bandit
          bandit -r app || echo "Security check completed"

      - name: 📝 Generate changelog
        run: |
          echo "## 📦 Changelog - $(date)" > changelog.md
          git log -1 --pretty=format:"%h %s (%an)" >> changelog.md

      - name: 🐳 Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pipeline-app:${{ github.run_number }} .

      - name: 🔐 Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 📤 Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pipeline-app:${{ github.run_number }}

      - name: 📢 Notify Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          NEW_VERSION: v${{ github.run_number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          RELEASE_URL: https://github.com/${{ github.repository }}/releases/tag/v${{ github.run_number }}
        run: |
          python scripts/notify_telegram.py

      - name: 🏷️ Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Release v${{ github.run_number }}"
          body_path: changelog.md
